[tool.black]
line-length = 120

[tool.isort]
profile = "black"
force_single_line = true
lines_after_imports = 2

## [tool.ruff]

[tool.lint.pydocstyle]
convention = "pep257"

[tool.mypy]
disable_error_code = ["arg-type", "import-untyped"] 